nacos:
  ip: 192.168.31.94
  port: 8848
  timeoutMs: 5000
  notLoadCacheAtStart: true
  logDir: ./logs
  cacheDir: ./configs/nacos
  logLevel: debug
  nameSpace: f320980d-d47e-4b63-896e-29879ea5a72e
  dataID: app.dev.yaml
  group: dev

lol:
  nameSpace: f320980d-d47e-4b63-896e-29879ea5a72e
  dataID: lol_config
  group: dev

equip:
  nameSpace: f320980d-d47e-4b63-896e-29879ea5a72e
  dataID: lol_equip_dict
  group: dev

spider:
  nameSpace: f320980d-d47e-4b63-896e-29879ea5a72e
  dataID: spider_cfg
  group: dev